#ifndef LOG_H
#define LOG_H

#include <QLoggingCategory>
Q_DECLARE_LOGGING_CATEGORY(log1)
Q_DECLARE_LOGGING_CATEGORY(demux)
Q_DECLARE_LOGGING_CATEGORY(adec)
Q_DECLARE_LOGGING_CATEGORY(vdec)



#endif // LOG_H
